#!/usr/bin/env python3
"""Generate COVERAGE.md from the shipped rule knowledge base and the analyzers'
actual rule maps, so the coverage table can never silently drift from the code.

Run `python tools/gen_coverage.py` to rewrite COVERAGE.md; a test asserts the
committed file matches this output. This is the honest answer to "which rules
do you actually cover" — the table is derived, not hand-maintained.

Analyzer backing, as the code (not the external tools) maps it:
  * native    — the deterministic, zero-dependency checks in native.py. The set
                is extracted from that file's own rule queries, so adding a check
                there updates this table on the next run.
  * cppcheck  — the MISRA addon emits by rule number (misra-c2012-N.N -> every
                MISRA *Rule*), plus the CERT ids in cppcheck's CPPCHECK_TO_CERT.
  * clang-tidy — cert-* checks map onto every CERT rule.
Whether a given cppcheck/clang-tidy rule actually fires depends on that external
engine's own coverage; this table reflects what Sentinel-C maps, not a promise
the engine implements every one.
"""
from __future__ import annotations

import re
from importlib import resources
from pathlib import Path

from sentinelc.rules import REGISTRY
from sentinelc.analyzers.cppcheck import CPPCHECK_TO_CERT

ROOT = Path(__file__).resolve().parent.parent
STANDARDS = ["MISRA-C:2012", "BARR-C:2018", "CERT-C"]
# MISRA category ordering: mandatory cannot be waived, so it must lead.
_CAT_ORDER = {"mandatory": 0, "required": 1, "advisory": 2, "": 3}


def native_ids() -> set[str]:
    """Canonical ids the native analyzer can emit, read from its own source."""
    src = (ROOT / "sentinelc" / "analyzers" / "native.py").read_text("utf-8")
    ids = set()
    for q in re.findall(r'"((?:MISRA|CERT|BARR)[^"]*)"', src):
        meta = REGISTRY.resolve(q)
        if meta:
            ids.add(meta["id"])
    return ids


def analyzers_for(meta: dict, native: set[str]) -> list[str]:
    rid, std = meta["id"], meta["standard"]
    out = []
    if rid in native:
        out.append("native")
    if std == "MISRA-C:2012" and rid.startswith("MISRA-C:2012 Rule "):
        out.append("cppcheck")
    if std == "CERT-C":
        out.append("clang-tidy")
        if any(f"CERT {c}" == rid for c in CPPCHECK_TO_CERT.values()):
            out.append("cppcheck")
    return out


def rows(standard: str, native: set[str]) -> list[tuple]:
    out = []
    for rid in REGISTRY.all_ids(standard):
        m = REGISTRY.get(rid)
        cat = m.get("category", "")
        out.append((_CAT_ORDER.get(cat, 3), rid,
                    (cat or "-"), m.get("severity", "-"),
                    ", ".join(analyzers_for(m, native)) or "**not detected**",
                    m.get("summary", "")))
    return sorted(out, key=lambda r: (r[0], r[1]))


def render() -> str:
    native = native_ids()
    L = ["# Rule Coverage",
         "",
         "> Generated by `tools/gen_coverage.py` from the shipped rule knowledge",
         "> base and the analyzers' rule maps. Do not edit by hand — run the",
         "> generator. A test (`test_coverage_doc_is_current`) fails if this file",
         "> drifts from the code.",
         "",
         "**This is a curated subset, and says so.** The full standards are far",
         "larger than what ships here — MISRA C:2012 has 180+ rules/directives and",
         "CERT C has hundreds of guidelines. The tables below list exactly the rules",
         "Sentinel-C carries fix guidance and cross-references for. A gap here is a",
         "known gap, which is the point: no silent \"we cover MISRA\" claim.",
         "",
         "**Analyzer columns** reflect what the code *maps*, not what an external",
         "engine guarantees to implement. `native` = the zero-dependency checks that",
         "run everywhere. `cppcheck` (MISRA addon + CERT map) and `clang-tidy`",
         "(`cert-*`) extend detection when installed; whether a specific rule fires",
         "is up to that engine.",
         ""]
    total = 0
    for std in STANDARDS:
        rs = rows(std, native)
        total += len(rs)
        nat = sum(1 for r in rs if "native" in r[4])
        L += [f"## {std} — {len(rs)} rules ({nat} detected with zero dependencies)",
              "",
              "| Rule | Category | Severity | Detected by | Summary |",
              "|------|----------|----------|-------------|---------|"]
        for _, rid, cat, sev, an, summ in rs:
            summ = summ.replace("|", "\\|")
            L.append(f"| {rid} | {cat} | {sev} | {an} | {summ} |")
        L.append("")
    L.insert(len(L), f"_Total: {total} rules across {len(STANDARDS)} standards._")
    L.append("")
    return "\n".join(L)


def main() -> None:
    out = ROOT / "COVERAGE.md"
    out.write_text(render(), "utf-8")
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
