#!/usr/bin/env python3
"""Generate COVERAGE.md from the shipped rule knowledge base and the analyzers'
actual rule maps, so the coverage table can never silently drift from the code.

Run `python tools/gen_coverage.py` to rewrite COVERAGE.md; a test asserts the
committed file matches this output. This is the honest answer to "which rules
do you actually cover" — the table is derived, not hand-maintained.

Analyzer backing, as the code (not the external tools) maps it:
  * native    — the deterministic, zero-dependency checks in native.py. The set
                is extracted from that file's own rule queries, so adding a check
                there updates this table on the next run.
  * cppcheck  — the MISRA rules its addon actually implements
                (CPPCHECK_MISRA_IMPLEMENTED, read off addons/misra.py), plus the
                CERT ids in cppcheck's CPPCHECK_TO_CERT.
  * clang-tidy — the CERT rules it ships a cert-* check for
                (CLANG_TIDY_CERT_RULES) — 18 rules, not "all of CERT".
Both external columns were blanket claims until Phase 0 of the rule-set
expansion: every MISRA Rule was credited to cppcheck and every CERT rule to
clang-tidy. Neither was true, so they are now closed lists derived from what
those tools publish. Even so, a check being *present* is not a guarantee it
fires on a given construct — these lists are an upper bound on external
coverage, not a promise.
"""
from __future__ import annotations

from pathlib import Path

from maishac.rules import REGISTRY
from maishac.coverage import native_ids, analyzers_for

ROOT = Path(__file__).resolve().parent.parent
STANDARDS = ["MISRA-C:2012", "BARR-C:2018", "CERT-C"]
# MISRA category ordering: mandatory cannot be waived, so it must lead.
_CAT_ORDER = {"mandatory": 0, "required": 1, "advisory": 2, "": 3}


def rows(standard: str, native: set[str]) -> list[tuple]:
    out = []
    for rid in REGISTRY.all_ids(standard):
        m = REGISTRY.get(rid)
        cat = m.get("category", "")
        out.append((_CAT_ORDER.get(cat, 3), rid,
                    (cat or "-"), m.get("severity", "-"),
                    ", ".join(analyzers_for(rid, native)) or "**not detected**",
                    m.get("summary", "")))
    return sorted(out, key=lambda r: (r[0], r[1]))


def render() -> str:
    native = native_ids()
    L = ["# Rule Coverage",
         "",
         "> Generated by `tools/gen_coverage.py` from the shipped rule knowledge",
         "> base and the analyzers' rule maps. Do not edit by hand — run the",
         "> generator. A test (`test_coverage_doc_is_current`) fails if this file",
         "> drifts from the code.",
         "",
         "**This is a curated subset, and says so.** The full standards are far",
         "larger than what ships here — MISRA C:2012 has 180+ rules/directives and",
         "CERT C has hundreds of guidelines. The tables below list exactly the rules",
         "Maisha carries fix guidance and cross-references for. A gap here is a",
         "known gap, which is the point: no silent \"we cover MISRA\" claim.",
         "",
         "**Analyzer columns** are closed lists of what each engine actually",
         "implements, not a blanket claim. `native` = the zero-dependency checks",
         "that run everywhere. `cppcheck` = the MISRA rules its addon really",
         "implements (it covers MISRA C:2012+AMD1/2 only — *no* AMD3/AMD4 rule is",
         "ever credited to it) plus our own map from its native error ids onto",
         "CERT rules. `clang-tidy` = the 18 CERT rules it ships a `cert-*` check",
         "for — not all of CERT.",
         "",
         "A check being present still isn't a guarantee it fires on a given",
         "construct, so treat the external columns as an upper bound. `**not",
         "detected**` means no engine we know of covers the rule: the entry is",
         "carried for cross-referencing, deviation records and SARIF import.",
         ""]
    total = 0
    for std in STANDARDS:
        rs = rows(std, native)
        total += len(rs)
        nat = sum(1 for r in rs if "native" in r[4])
        L += [f"## {std} — {len(rs)} rules ({nat} detected with zero dependencies)",
              "",
              "| Rule | Category | Severity | Detected by | Summary |",
              "|------|----------|----------|-------------|---------|"]
        for _, rid, cat, sev, an, summ in rs:
            summ = summ.replace("|", "\\|")
            L.append(f"| {rid} | {cat} | {sev} | {an} | {summ} |")
        L.append("")
    L.insert(len(L), f"_Total: {total} rules across {len(STANDARDS)} standards._")
    L.append("")
    return "\n".join(L)


def main() -> None:
    out = ROOT / "COVERAGE.md"
    out.write_text(render(), "utf-8")
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
